services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    secrets:
      - discord_webhook_url
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    restart: unless-stopped

secrets:
  discord_webhook_url:
    file: ./secrets/discord_webhook_url
